### ISSUE TITLE
dynamic URL in Shiny back and forth

### ISSUE THREAD

**Issue by pachamaltese** [tradestatistics/shiny-app#4]
@jbkunst you are gonna like this !!!
after reading how bookmarking works and adapting old Shiny tricks I got this: https://shiny.tradestatistics.io/#y=2016&r=jpn
if you click and select another country the URL will be updated (tested on firefox) by using some javascript (not even `shinyjs`)
anyways, i would be cool to fix this
https://github.com/tradestatistics/shiny-app/blob/465a4d74c351a22e6fcb32489cee7e1f464213b8/app.R#L121-L135

**Comment by pachamaltese** [comment]
@aedobbyn provided that you are the ROpenSci expert here, do you think it would be acceptable to suggest Shiny geniuses to implement this auto-URL function by default in Shiny?

**Comment by aedobbyn** [comment]
@pachamaltese you mean suggesting to the Shiny core team that they implement a way to update the app url when a different reactive value is provided by the end user?

**Comment by pachamaltese** [comment]
Exactly? Something like "auto bookmarking" or any function like that

**Comment by aedobbyn** [comment]
Sounds like it could be useful! I think you could safely open an issue in the Shiny repo to suggest it if you provide some reproducible example code and a good argument for how others would use it.
